### ISSUE TITLE
Shortcuts in the console not working well after installing cloud native toolkit

### ISSUE THREAD

**Issue by faysou** [cloud-native-toolkit/toolkit-charts#239]
I don't know if this is the right place to enter the issue.

After installing the cloud native toolkit as explained here
https://cloudnativetoolkit.dev/setup/fast-start/
curl -sfL get.cloudnativetoolkit.dev | sh -

the shortcuts at the top right of my openshift console all have an added router-default in the urls
https://pact-broker-tools.router-default.apps.ocp.mydomain.com

![image](https://user-images.githubusercontent.com/893862/132554577-9a5900cc-ba91-4cbe-8504-9be8ec0ba1e4.png)

So the shortcuts are not working, but if I remove router-default from the url, the services are well installed.
https://pact-broker-tools.apps.ocp.mydomain.com

Can somebody check if they can reproduce this bug ?

Thank you

**Comment by csantanapr** [comment]
@lsteck could you take a look at this?

**Comment by faysou** [comment]
router-default also appears in configs, I tried the golang example project. There must be an internal variable badly defined, but I have no idea where it could be, it's a complex set of tools and I'm just beginning.

**Comment by lsteck** [comment]
@faysou Thanks for the find.  FYI we are going to restructure how this works to query the routes after the tools are installed.

**Comment by faysou** [comment]
Thank you for your answer, then I'll wait for your reply to this thread when this has been fixed so I can reinstall the tool (it seems very interesting as a starting point).

**Comment by faysou** [comment]
Do you have an idea on when this could be resolved ? This doesn't have an impact on just shortcuts, all generated yamls point to wrong adresses as well.

**Comment by lsteck** [comment]
Hi @faysou,

It should be working now.  I just tested it myself.  When you do an install you should see a console link cronjob that is configured to update links based on the routes.

**Comment by faysou** [comment]
It works indeed, I've just tested on my installation. Thank you very much for your help.

**Comment by faysou** [comment]
Actually this one doesn't work 
https://dashboard-tools.router-default.apps.ocp.mydomain.com
